pipeline {
  agent any

  tools {
    go 'go-1.22'
  }

  options {
    timestamps()
    disableConcurrentBuilds()
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Test') {
      steps {
        sh 'go test ./...'
      }
    }

    stage('Build') {
      steps {
        sh 'go build ./cmd/server'
      }
    }
  }

  post {
    always {
      archiveArtifacts artifacts: 'server', fingerprint: true
    }
  }
}
