name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '__JAVA_VERSION__'
          cache: maven

      - name: Test
        run: ./mvnw -B test

      - name: Build
        run: ./mvnw -B -DskipTests package
