# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  Startup Scripts
#  Sources all scripts that should be executed once on startup.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Core Daemons (Authentication, DBus, etc.)
exec-once = ./scripts/startup/00-keyring.sh
exec-once = ./scripts/startup/01-polkit.sh
exec-once = ./scripts/startup/02-dbus.sh

# Environment & Services
exec-once = ./scripts/startup/10-geolocation.sh
exec-once = ./scripts/startup/11-input-method.sh
exec-once = ./scripts/startup/12-clipboard.sh
exec-once = ./scripts/startup/13-audio.sh

# Hyprland Specific Daemons
exec-once = ./scripts/startup/20-hypr-daemons.sh

# UI & Theming
exec-once = ./scripts/startup/30-wallpaper.sh
exec-once = ./scripts/startup/31-cursor.sh
exec-once = ./scripts/startup/32-xhost.sh

exec-once = ./scripts/startup/99-quickshell.sh

# DISABLED: Video wallpaper script depends on missing 'switchwall.sh'.
# exec-once = bash ./scripts/wallpaper/__restore_video_wallpaper.sh
