alias shutdown='systemctl poweroff'
alias reboot='systemctl reboot'
alias suspend='systemctl suspend'

alias p='sudo pacman'
alias pi='sudo pacman -S'
alias pr='sudo pacman -Rns'
alias pu='sudo pacman -Syu'
alias ps='pacman -Ss'
alias pq='pacman -Q'
alias pc='sudo pacman -Scc'

alias y='yay'
alias yi='yay -S'
alias yu='yay -Syu'

alias ls='eza --icons --group-directories-first'
alias ll='eza -lah --icons --group-directories-first'
alias lt='eza --tree --level=2 --icons'

alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -Iv'
alias mkdir='mkdir -pv'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias dots='cd ~/dotfiles'
alias dl='cd ~/Downloads'
alias dev='cd ~/Dev'
alias games='cd ~/Games'

alias g='git'
alias ga='git add'
alias gc='git commit -m'
alias gp='git push'
alias gl='git pull'
alias gs='git status'
alias gd='git diff'
alias gco='git checkout'
alias gb='git branch'
alias glog='git log --oneline --graph --decorate'

alias v='nvim'
alias vim='nvim'
alias d='docker'
alias dc='docker-compose'
alias dps='docker ps'
alias di='docker images'
alias j='just'

alias niri-reload='niri msg reload-config'
alias niri-validate='niri validate -c ~/.config/niri/config.kdl.active'
alias niri-log='journalctl --user -u niri -f'

alias ctx='context-switch'
alias ctx-dev='context-switch dev'
alias ctx-game='context-switch game'
alias ctx-default='context-switch default'
alias ctx-status='context-switch status'

alias game='game-launcher'
alias perf='neon-perfmon'

alias c='clear'
alias h='history'
alias grep='grep --color=auto'
alias df='df -h'
alias du='du -h'
alias free='free -h'
alias myip='curl -s ifconfig.me'
alias ports='ss -tulanp'
