background = #050608
foreground = #f7f8fb
cursor-color = #ff4357
selection-background = #1f2a3a
selection-foreground = #f7f8fb

palette = 0=#050608
palette = 1=#b32428
palette = 2=#3a8f6b
palette = 3=#b9681e
palette = 4=#114a6b
palette = 5=#703c81
palette = 6=#0f6c75
palette = 7=#d1d4dc
palette = 8=#181b23
palette = 9=#ff4357
palette = 10=#4fbf90
palette = 11=#f4a259
palette = 12=#1f6db5
palette = 13=#b980ff
palette = 14=#19a8c7
palette = 15=#f7f8fb
