background = #000000
foreground = #E6F5FF
cursor-color = #5BFF8F
selection-background = #0a1320
selection-foreground = #E6F5FF

palette = 0=#000000
palette = 1=#FF4B6E
palette = 2=#41FF7C
palette = 3=#C5FF5E
palette = 4=#25B7FF
palette = 5=#A071FF
palette = 6=#00F5FF
palette = 7=#E6F5FF
palette = 8=#1C2433
palette = 9=#FF6F8F
palette = 10=#7CFF9E
palette = 11=#E0FF7F
palette = 12=#6BD3FF
palette = 13=#CDA5FF
palette = 14=#66F9FF
palette = 15=#FFFFFF
