# Base Kitty config (stable, no self-links)
font_family      DankMono Nerd Font
bold_font        DankMono Nerd Font Bold
italic_font      DankMono Nerd Font Italic
bold_italic_font DankMono Nerd Font Bold Italic
font_size        11.5
term xterm-256color
shell zsh
mouse_hide_wait 0.5
scrollback_lines 10000
remember_window_size yes
initial_window_width  1600
initial_window_height 900
window_padding_width 14
window_border_width 1.0
draw_minimal_borders yes
hide_window_decorations yes
enable_audio_bell no
visual_bell_duration 0
allow_remote_control yes
listen_on unix:/tmp/kitty-$UID
kitty_mod ctrl+shift
