# Red Hood / Batman palette
foreground #e6edf3
background #0a0b0d
background_opacity 0.92
selection_foreground #0a0b0d
selection_background #dc143c
cursor #ff073a
cursor_text_color #0a0b0d
color0  #0a0b0d
color1  #dc143c
color2  #22e3b3
color3  #facc15
color4  #22d3ee
color5  #7c3aed
color6  #ee79d1
color7  #e6edf3
color8  #1f232a
color9  #ff073a
color10 #44f7c5
color11 #ffd95a
color12 #44e6ff
color13 #a98bff
color14 #ff9eeb
color15 #ffffff
active_tab_foreground   #000000
active_tab_background   #dc143c
inactive_tab_foreground #666666
inactive_tab_background #1f232a
