#!/usr/bin/env bash
#───────────────────────────────────────────────────────────────────────
# bootstrap_niri.sh — integrate Niri + auxiliaries into dotfiles
#───────────────────────────────────────────────────────────────────────
set -euo pipefail

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
CYAN='\033[1;36m'
RED='\033[1;31m'
NC='\033[0m'

info()    { printf "${CYAN}[INFO]${NC} %s\n" "$*"; }
success() { printf "${GREEN}[ OK ]${NC} %s\n" "$*"; }
warn()    { printf "${YELLOW}[WARN]${NC} %s\n" "$*"; }
fatal()   { printf "${RED}[FAIL]${NC} %s\n" "$*" >&2; exit 1; }

#───────────────────────────────────────────────────────────────────────
# Phase 1 — preparation
#───────────────────────────────────────────────────────────────────────
DEFAULT_DOTFILES="${DOTFILES_DIR:-}"
if [[ -z "$DEFAULT_DOTFILES" ]]; then
    if [[ -d "$HOME/my_dotfiles" ]]; then
        DEFAULT_DOTFILES="$HOME/my_dotfiles"
    else
        DEFAULT_DOTFILES="$HOME/workstation"
    fi
fi
DOTFILES_DIR="$DEFAULT_DOTFILES"
[[ -d "$DOTFILES_DIR" ]] || fatal "Dotfiles directory not found: $DOTFILES_DIR"

TMP_DIR="${TMP_DIR:-/tmp/niri_bootstrap}"
SHELL_REPO="$TMP_DIR/shell-ninja"
ACAI_REPO="$TMP_DIR/acaibowlz"
CONFIG_DIR="$DOTFILES_DIR/config"
NIRI_DIR="$CONFIG_DIR/niri"
NIRI_SCRIPTS="$NIRI_DIR/scripts"
WAYBAR_DIR="$CONFIG_DIR/waybar"
DUNST_DIR="$CONFIG_DIR/dunst"

for bin in git rsync python3; do
    command -v "$bin" >/dev/null 2>&1 || fatal "Missing dependency: $bin"
done

cleanup() {
    rm -rf "$TMP_DIR"
}
trap cleanup EXIT

info "Cleaning temp workspace"
rm -rf "$TMP_DIR"
mkdir -p "$TMP_DIR"
cd "$TMP_DIR"

clone_repo() {
    local url="$1" dest="$2"
    if [[ -d "$dest/.git" ]]; then
        info "Updating $dest"
        (cd "$dest" && git pull --ff-only >/dev/null)
    else
        info "Cloning $url"
        git clone --depth=1 "$url" "$dest" >/dev/null
    fi
}

clone_repo "https://github.com/shell-ninja/niriconf.git" "$SHELL_REPO"
clone_repo "https://github.com/acaibowlz/niri-setup.git" "$ACAI_REPO"

#───────────────────────────────────────────────────────────────────────
# Helpers
#───────────────────────────────────────────────────────────────────────
safe_overwrite() {
    local target="$1"
    local tmp
    tmp=$(mktemp)
    cat >"$tmp"
    if [[ -f "$target" ]]; then
        if cmp -s "$tmp" "$target"; then
            rm -f "$tmp"
            return
        fi
        local backup="$target.backup.$(date +%Y%m%d-%H%M%S)"
        cp "$target" "$backup"
        warn "Updated $target (backup: $backup)"
    fi
    mkdir -p "$(dirname "$target")"
    mv "$tmp" "$target"
}

sync_from_repo() {
    local repo="$1" pattern="$2" dest="$3" label="$4"
    local src
    src=$(find "$repo" -type d -path "*$pattern" | head -n1 || true)
    if [[ -z "$src" ]]; then
        warn "No ${label} assets found in ${repo##*/} (pattern: $pattern)"
        return 0
    fi
    mkdir -p "$dest"
    rsync -a --ignore-existing "$src"/ "$dest"/
    success "Merged $label from ${src/$TMP_DIR\//}"
}

ensure_symlink_entry() {
    local name="$1"
    local module="$DOTFILES_DIR/install/modules/symlinks.sh"
    [[ -f "$module" ]] || fatal "Missing $module"
    python3 <<PY
import re
from pathlib import Path
path = Path("${module}")
text = path.read_text()
pattern = r'(local -a configs=\(\n)([\s\S]*?)(\n\))'
m = re.search(pattern, text)
if not m:
    raise SystemExit(0)
body = m.group(2).splitlines()
items = []
for line in body:
    stripped = line.strip()
    if stripped:
        items.append(stripped)
names = [line.split()[0] for line in items]
if "${name}" not in names:
    items.append("${name}")
    new_body = ''.join(f"        {entry}\n" for entry in dict.fromkeys(items))
    text = text[:m.start(2)] + new_body + text[m.end(2):]
    path.write_text(text)
PY
}

ensure_wrapper_symlink_script() {
    local wrapper="$DOTFILES_DIR/scripts/create-symlinks.sh"
    if [[ ! -f "$wrapper" ]]; then
        mkdir -p "$DOTFILES_DIR/scripts"
        cat >"$wrapper" <<'WRAP'
#!/usr/bin/env bash
set -euo pipefail
REPO_DIR="${1:-$(cd -- "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
source "$REPO_DIR/install/modules/symlinks.sh"
create_symlinks "$REPO_DIR"
WRAP
        chmod +x "$wrapper"
        success "Created $wrapper"
    fi
}

#───────────────────────────────────────────────────────────────────────
# Phase 2 — architecture & asset generation
#───────────────────────────────────────────────────────────────────────
info "Preparing directory structure"
mkdir -p "$NIRI_SCRIPTS" "$WAYBAR_DIR" "$DUNST_DIR"

safe_overwrite "$NIRI_DIR/config.kdl" <<'KDL'
// Niri powerhouse configuration — generated by bootstrap_niri.sh
config-notification { disable-failed }

environment {
    XDG_CURRENT_DESKTOP "niri"
    XDG_SESSION_TYPE "wayland"
    QT_QPA_PLATFORM "wayland"
    QT_AUTO_SCREEN_SCALE_FACTOR "1"
    ELECTRON_OZONE_PLATFORM_HINT "wayland"
    TERMINAL "ghostty"
    EDITOR "nvim"
}

output "DP-1" {
    transform "normal"
    position x=0 y=0
    scale 1.0
}
output "HDMI-A-1" {
    transform "normal"
    position x=1920 y=0
    scale 1.0
}

input {
    keyboard {
        xkb { layout "br" }
        repeat-rate 35
        repeat-delay 350
    }
    pointer { accel-profile "adaptive" }
    focus-follows-mouse
}

layout {
    gaps 8
    background-color "#0d0d16e6"
    center-focused-column "on-overflow"
    default-column-width { proportion 0.55; }
    preset-column-widths { proportion 0.33; proportion 0.5; proportion 0.67; }
    shadow { softness 30; spread 6; offset x=0 y=6; color "#000a"; }
    border {
        width 2
        active-color   "#4fd2ff"
        inactive-color "#22242d"
        urgent-color   "#f7768e"
    }
}

spawn-at-startup "bash" "-lc" "~/.config/niri/scripts/autostart.sh"

screenshot-path "~/Pictures/Screenshots/niri-%Y%m%d-%H%M%S.png"
prefer-no-csd

window-rule { match app-id=r#"^(?:steam|pavucontrol|gnome-control-center)$"#; open-floating true; }
window-rule { match app-id=r#"^firefox$"# title="^(?:Picture-in-Picture)$"; open-floating true; }
window-rule { match app-id=r#"^(?:kitty|ghostty|wezterm|code)$"#; draw-border-with-background false; }
window-rule { match is-active=false; opacity 0.92; }
window-rule { geometry-corner-radius 10; clip-to-geometry true; }

workspaces {
    workspace 1 { name "term"; default-column-width { proportion 0.60; } }
    workspace 2 { name "code"; }
    workspace 3 { name "web"; }
    workspace 4 { name "chat"; }
    workspace 5 { name "media"; }
    workspace 6 { name "infra"; }
}

binds {
    Mod+Return { spawn "ghostty"; }
    Mod+Shift+Return { spawn "kitty"; }
    Mod+Space { spawn "fuzzel"; }
    Mod+B { spawn "firefox"; }
    Mod+Shift+C { spawn "code"; }
    Mod+Shift+G { spawn "gamescope" "-f" "-w" "1920" "-h" "1080" "--" "steam" "-bigpicture"; }

    Mod+Q { close-window; }
    Mod+Shift+Q { quit; }
    Mod+F { maximize-column; }
    Mod+Shift+F { fullscreen-window; }
    Mod+Shift+T { toggle-window-floating; }

    Mod+H { focus-column-left; }
    Mod+L { focus-column-right; }
    Mod+J { focus-window-down; }
    Mod+K { focus-window-up; }
    Mod+Shift+H { move-column-left; }
    Mod+Shift+L { move-column-right; }
    Mod+Shift+J { move-window-down; }
    Mod+Shift+K { move-window-up; }

    Mod+Page_Down { focus-workspace-down; }
    Mod+Page_Up { focus-workspace-up; }
    Mod+Ctrl+Page_Down { move-column-to-workspace-down; }
    Mod+Ctrl+Page_Up { move-column-to-workspace-up; }

    Mod+1 { focus-workspace 1; }
    Mod+2 { focus-workspace 2; }
    Mod+3 { focus-workspace 3; }
    Mod+4 { focus-workspace 4; }
    Mod+5 { focus-workspace 5; }
    Mod+6 { focus-workspace 6; }

    Mod+Shift+1 { move-column-to-workspace 1; }
    Mod+Shift+2 { move-column-to-workspace 2; }
    Mod+Shift+3 { move-column-to-workspace 3; }
    Mod+Shift+4 { move-column-to-workspace 4; }
    Mod+Shift+5 { move-column-to-workspace 5; }
    Mod+Shift+6 { move-column-to-workspace 6; }

    XF86AudioLowerVolume { spawn "wpctl" "set-volume" "@DEFAULT_AUDIO_SINK@" "-5%"; }
    XF86AudioRaiseVolume { spawn "wpctl" "set-volume" "@DEFAULT_AUDIO_SINK@" "+5%"; }
    XF86AudioMute        { spawn "wpctl" "set-mute" "@DEFAULT_AUDIO_SINK@" "toggle"; }
    XF86AudioMicMute     { spawn "wpctl" "set-mute" "@DEFAULT_AUDIO_SOURCE@" "toggle"; }

    Print { spawn "bash" "-lc" "grimblast save area ~/Pictures/Screenshots/grim-$(date +%s).png"; }
    Mod+Shift+S { spawn "bash" "-lc" "grimblast copy area"; }
}
KDL

safe_overwrite "$NIRI_SCRIPTS/autostart.sh" <<'SH'
#!/usr/bin/env bash
set -euo pipefail
log() { printf "[autostart] %s\n" "$*"; }
start() {
    local cmd="$1"; shift
    if pgrep -f "$cmd" >/dev/null 2>&1; then
        return
    fi
    ("$@" >/dev/null 2>&1 &) &
}

# Prepare session environment for portals/flatpak
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP || true
dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP >/dev/null 2>&1 || true

start wl-paste wl-paste --type text --watch cliphist store
start wl-paste wl-paste --type image --watch cliphist store
start cliphist cliphist daemon
start waybar waybar
start dunst dunst
start swaybg swaybg -m fill -i "$HOME/wallpapers/current.png"
start nm-applet nm-applet --indicator
start polkit /usr/lib/mate-polkit/polkit-mate-authentication-agent-1
start kanshi kanshi
start gammastep gammastep -O 4500
start syncthing syncthing serve --no-browser
SH
chmod +x "$NIRI_SCRIPTS/autostart.sh"

sync_from_repo "$SHELL_REPO" "waybar" "$WAYBAR_DIR" "Waybar"
sync_from_repo "$ACAI_REPO" "waybar" "$WAYBAR_DIR" "Waybar"
sync_from_repo "$SHELL_REPO" "dunst" "$DUNST_DIR" "Dunst"
sync_from_repo "$ACAI_REPO" "dunst" "$DUNST_DIR" "Dunst"

#───────────────────────────────────────────────────────────────────────
# Phase 3 — deployment & symlinks
#───────────────────────────────────────────────────────────────────────
ensure_symlink_entry "waybar"
ensure_symlink_entry "dunst"
ensure_symlink_entry "niri"
ensure_wrapper_symlink_script

info "Applying symlinks"
"$DOTFILES_DIR/scripts/create-symlinks.sh"

success "Niri stack bootstrapped"
